server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: example-service
          uri: lb://EXAMPLE-SERVICE
          predicates:
            - Path=/example/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/